# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=github.com/petar/GoHTTP/http
GOFILES=\
	abridge.go\
	aclient.go\
	aclientconn.go\
	aserver.go\
	aserverconn.go\
	boiler.go\
	chunked.go\
	client.go\
	dump.go\
	fdlimiter.go\
	fs.go\
	lex.go\
	persist.go\
	request.go\
	response.go\
	roc.go\
	server.go\
	status.go\
	transfer.go\
	url.go\

include $(GOROOT)/src/Make.pkg
