# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=github.com/petar/GoHTTP/http
GOFILES=\
	chunked.go\
	client.go\
	dump.go\
	fs.go\
	lex.go\
	persist.go\
	request.go\
	response.go\
	server.go\
	status.go\
	transfer.go\
	transport.go\
	url.go\
	petar-util.go\
	petar-boiler.go\
	cookie.go\
	header.go\
	reverseproxy.go\

include $(GOROOT)/src/Make.pkg
