# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=github.com/petar/GoHTTP/server/rpc
GOFILES=\
	rpc.go\

include $(GOROOT)/src/Make.pkg
